version: "3.9"

services:
  x-backend: &backend
    stdin_open: true
    tty: true
    build: .
    environment: &env
      PGPASSWORD: password

  db:
    <<: *backend
    image: postgres
    volumes:
      - ./log:/root/log:cached
      - ./.psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      - postgres_history:/var/log/psql_history
    ports:
      - 5432
    environment:
      <<: *env
      POSTGRES_PASSWORD: password
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    <<: *backend
    environment:
      <<: *env
      SSH_AUTH_SOCK: /ssh/auth/sock
      EDITOR: vim
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - ssh-data:/ssh:ro
    ports:
      - "3000:3000"
    depends_on:
      - db

  webpack:
    <<: *backend
    command: ./bin/webpack-dev-server --host=0.0.0.0 --disable-host-check
    ports:
      - '3035:3035'
    volumes:
      - ..:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - packs-test:/app/public/packs-test
    depends_on:
      - web

volumes:
  postgres:
  postgres_history:
  bundle:
  rails_cache:
  node_modules:
  packs:
  packs-test:
  ssh-data:
    external:
      name: ssh_data
